name: build package

on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: brew install dpkg create-dmg ldid ruby
      - name: ruby
        run: | 
           gem install bundler
           bundle config set --local path '.bundle/vendor'
           bundle install
      - name: Set Default Scheme
        run: |
          xcodebuild archive -project AdguardExtension/Adguard.xcodeproj -scheme "AdguardPro" -xcconfig "AdguardExtension/AdguardPro/Adguard-Pro.xcconfig" CODE_SIGNING_REQUIRED=NO CODESIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=
